export const photos = {
  kiss: "/photos/kiss.webp",
  manor: "/photos/manor.webp",
  walkToward: "/photos/walk-toward.webp",
  lakeTerrace: "/photos/lake-terrace.webp",
  lookBack: "/photos/look-back.webp",
  steps: "/photos/steps.webp",
  overlook: "/photos/overlook.webp",
  flow1: "/photos/flow-1.webp",
  flow2: "/photos/flow-2.webp",
  flow3: "/photos/flow-3.webp",
  flow4: "/photos/flow-4.webp",
  guestViewPhone: "/photos/guest-view.webp",
  uploadPhone: "/photos/upload-iphone.webp",
} as const;
